repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
      - id: end-of-file-fixer
      # - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending

  - repo: https://github.com/psf/black.git
    rev: 23.3.0
    hooks:
      - id: black
        args: [--line-length=120]
        stages: [commit, push]

  - repo: https://github.com/pycqa/isort.git
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        additional_dependencies: ["tomli"]

  - repo: https://github.com/myint/docformatter.git
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: ["--in-place", "--black"]
