[tool.black]
line-length = 120
target-version = ['py38', 'py39', 'py310']
include = '\.pyi?$'
skip-string-normalization = true


[tool.ruff]
line-length = 120
# Always autofix, but never try to fix:
# - `F401` (unused imports)
# - `F841` (unused variables)
fix = true
unfixable = ["F401", "F841"]
# Assume the minimum version is Python 3.8
target-version = 'py38'


[tool.isort]
line_length = 120
profile = "black"
src_paths = ["."]

[tool.codespell]
ignore-words-list = "shs,SHs,transfert"
